### ISSUE TITLE
Problem on install

### ISSUE THREAD

**Issue by Z33DD** [berty/go-orbit-db#40] opened 2020-06-06 01:05 UTC
I'm trying to install, but I get this error.
```bash
$ go get berty.tech/go-orbit-db
# github.com/ipfs/go-ipfs-blockstore
../../.go/src/github.com/ipfs/go-ipfs-blockstore/bloom_cache.go:90:12: log.EventBegin undefined (type *log.ZapEventLogger has no field or method EventBegin)
```
PS: I'm newbie in Golang

**Comment by gfanton** [comment] 2021-03-24 16:15
Sorry for the response time, we didn't have an effective process or notification system set up to handle issues and PRs from the community. From now on we should be much more responsive.

Has of today, i was not able to reproduce this issue. closing for now.
If you still have an issue, feel free to open it again

**Closed by gfanton** 2021-03-24 16:15 UTC
